(DEFUN CONTINE-NUMAR(L)
(COND
 ((NULL L) NIL)
 ((NUMBERP (CAR L)) T)
 ((ATOM (CAR L)) (CONTINE-NUMAR (CDR L)))
 (T (OR (CONTINE-NUMAR (CAR L)) (CONTINE-NUMAR (CDR L))))
)
)
 
(DEFUN VERIF(L)
(COND
 ((NULL L) NIL)
 ((AND (NUMBERP (CAR L)) (NOT (CONTINE-NUMAR (CDR L)))) (EQUAL 1 (MOD (CAR L) 2)))
 ((ATOM (CAR L)) (VERIF (CDR L)))
 ((AND (LISTP (CAR L)) (NOT (CONTINE-NUMAR (CDR L)))) (VERIF (CAR L)))
 (T (VERIF (CDR L)))
)
)
 
(DEFUN NUMAR(L)
(COND
 ((ATOM L) 0)
 ((VERIF L) (+ 1 (APPLY '+ (MAPCAR #'NUMAR L))))
 (T (APPLY '+ (MAPCAR #'NUMAR L)))
)
)
 
(DEFUN START(L) (APPLY '+ (MAPCAR #'NUMAR L)))

