# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for exam
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  
end
